config/routes.rb
Rails.application.routes.draw do
  
  devise_for :collection_managers
  devise_for :admin_users

  root 'dashboard#index'
    get 'completed' => "dashboard#completed"

  resources :admin_users do
    resources :collection_managers do
    end
  end

  resources :collection_managers, shallow: true do
    resources :clients do
        get 'profile' => "clients#profile"
      resources :pieces do
        get 'garments', on: :collection
        get 'bags', on: :collection
        get 'shoes', on: :collection
        get 'accessories', on: :collection
      end
      resources :deliveries do
        get 'completed_deliveries', on: :collection
        collection do
            put :completed
        end
          get 'check_out_pieces' => "deliveries#check_out"
          put 'complete_check_out' => "deliveries#complete_check_out"
          put 'remove_piece' => 'deliveries#remove'
        end
      resources :pickups do
        get 'completed_pickups', on: :collection
        collection do
            put :completed
        end
        get 'check_in_pieces' => "pickups#check_in"
        put 'complete_check_in' => "pickups#complete_check_in"
        put 'remove_piece' => 'pickups#remove'
        resources :pieces
      end
    end
  end
end

app/models/pickup.rb
class Pickup < ActiveRecord::Base
  belongs_to :client
  has_many :pieces

  validates :date, presence: true
  validates :piececount, presence: true

end

app/controllers/pickups_controller.rb
class PickupsController < ApplicationController

	def index
		@collection_manager = current_collection_manager
		@client = @collection_manager.clients.find(params[:client_id])
		@pickups = @client.pickups
		@pending_pickups = @pickups.where(completed: false)

	end

	def show
		@pickup = Pickup.find(params[:id])
		@client_name = @pickup.client.name
		@client_id = @pickup.client_id

	end


	def new
		@client = Client.find(params[:client_id])
		@pickup = @client.pickups.new

	end

	def create
		@client = Client.find(params[:client_id])
		@pickup = @client.pickups.create(safe_pickup_params)
		if @pickup.save
			flash[:notice] = "Pickup created!"
			redirect_to pickup_path(@pickup)
		else
			flash[:alert] = "Please complete pickup form!"
			render :new
		end
	end

	def edit
		@pickup = Pickup.find(params[:id])
		@client = @pickup.client
	end

	def update
		@pickup = Pickup.find(params[:id])
		if @pickup.update(safe_pickup_params)
			flash[:notice] = "Pickup Updated!"
			redirect_to pickup_path(@pickup)
		else
			render edit_pickup_path
		end
	end

	def check_in
		@pickup = Pickup.find(params[:pickup_id])	
		@client = Client.find(params[:client_id])
		@pieces = @client.pieces.where(location: 'At Client')
		
	end

	def complete_check_in
		@pickup = Pickup.find(params[:pickup_id])
		@client = @pickup.client_id
		Piece.where(id: params[:piece_ids]).update_all(location: "On Site", pickup_id: @pickup)
		redirect_to pickup_path(@pickup)

	end

	def completed
		@pickup = Pickup.find(params[:pickup_id])

		if @pickup.completed != true
			if @pickup.pieces.count != @pickup.piececount
				flash[:alert] = "Pieces in pickup must equal the number of associated pieces!"
				redirect_to pickup_path(@pickup)
			else
				@pickup.update(completed: true)
				flash[:notice] = "Pickup has been marked as complete!"
				redirect_to pickup_path(@pickup)
			end
		else
			@pickup.update(completed: false)
			redirect_to pickup_path(@pickup)
		end
	end

	def completed_pickups
		@client = Client.find(params[:client_id])
		@pickups = @client.pickups.where(completed: true)
	end

	def remove
		@pickup = Pickup.find(params[:pickup_id])
		@client = @pickup.client_id
		Piece.where(id: params[:piece_ids]).update_all(location: "On Site", pickup_id: 'nil')
		redirect_to pickup_path(@pickup)
	end

	def destroy
		@pickup = Pickup.find(params[:id]).destroy
		@client = @pickup.client
		redirect_to client_path(@client)
	end



	private

	def safe_pickup_params

		params.require(:pickup).permit(:date, :notes, :client_id, :piececount)

	end

end

app/views/pickups/check_in.html.erb
<h2>Check in Pieces for <%=@client.name%></h2>

<div class="col-md-2">
</div>

<div class="col-md-10">
	<h3>Pieces Currently At Client</h3>

	<% if @pieces == [] %>
		<br>There are currently no pieces to check in.</br>
	<%else%>
		<%= form_tag pickup_complete_check_in_path, method: :put do %>
			<%@pieces.each do |p|%>
				<ul class="all-pieces-grid">
			
					<%= link_to image_tag(p.photo), p %>
					<%= check_box_tag "piece_ids[]", p.id %> Piece #: <%= p.id %>
					<p><%= p.designer %></p>			
				</ul>
			<%end%>
			
			<p><%= submit_tag "Check In Pieces" %></p>
		<%end%>
	<%end%>

	<br><%=link_to "Return to Pickup Page", pickup_path(@pickup) %></br>
</div>

app/views/pickups/completed_pickups.html.erb
<h1> Completed Pickups for <%=@client.name%> </h1>

<div class="col-md-2">
	<p><%=link_to "+ New Pickup", new_client_pickup_path(@client)%></p>
</div>

<div class="col-md-10">

	<% if @pickups.blank? %>
		<p>All pickups are currently pending.</p>
	<% else %>

		<table class="table table-bordered table-striped">
			<thead>
				<tr>
					<th>Date</th>
					<th>Pickup Number</th>
					<th>Client</th>
					<th>Number of Pieces</th>
				</tr>
			</thead>
			<tbody>
					
				<%@pickups.each do |p|%>
					<tr>
						<td><%=link_to p.date.strftime("%m/%d/%Y"), p%></td>
						<td><%=p.id%></td>
						<td><%=p.client.name%></td>
						<td><%=p.piececount%></td>
					</tr>
				<%end%>
			</tbody>
		</table>
	<%end%>

<br><%=link_to "Return to Client Page", client_path(@client) %></br>

</div>

app/views/pickups/edit.html.erb
<h1> Edit Pickup </h1>

<%= form_for [@pickup] do |p|%>
	<p>Date: <%= p.date_select :date %></p>

	<p>Piece Count: <%= p.text_field :piececount %>
	<p>Notes: <%= p.text_area :notes %>
	

	<p><%= p.submit %></p>

<%end%>

app/views/pickups/index.html.erb
<h1> Pending Pickups for <%=@client.name%> </h1>

<div class="col-md-2">
	<p><%=link_to "+ New Pickup", new_client_pickup_path(@client)%></p>
	<p><%=link_to "Completed Pickups", completed_pickups_client_pickups_path(@client) %> </p>

</div>

<div class="col-md-10">

	<% if @pending_pickups.blank? %>
		<p>There are currently no pending pickups.</p>
	<% else %>
		<table class="table table-bordered table-striped">
			<thead>
				<tr>
					<th>Date</th>
					<th>Pickup Number</th>
					<th>Client</th>
					<th>Number of Pieces</th>
				</tr>
			</thead>
			<tbody>
					
				<%@pending_pickups.each do |p|%>
					<tr>
						<td><%=link_to p.date.strftime("%m/%d/%Y"), p%></td>
						<td><%=p.id%></td>
						<td><%=p.client.name%></td>
						<td><%=p.piececount%></td>
					</tr>
				<%end%>
			</tbody>
		</table>
	<%end%>

<br><%=link_to "Return to Client Page", client_path(@client) %></br>
</div>

app/views/pickups/new.html.erb
<h1> Create New Pickup for <%=@client.name %></h1>

<div class="col-md-10">

	<%= form_for [@client, @pickup] do |p|%>
		<p>Date: <%= p.date_select :date %></p>

		<p>Piece Count: <%= p.text_field :piececount %>
		<p>Notes: <%= p.text_area :notes %>
		

		<p><%= p.submit class: "btn btn-default btn-md"%></p>

	<%end%>

<br><%=link_to "Return to Client Page", client_path(@client) %></br>
</div>

app/views/pickups/show.html.erb
<h1> Pickup <%=@pickup.id%> on <%=@pickup.date.strftime("%m/%d/%Y") %> for <%=@client_name%></h1>

<% if @pickup.completed? %>
	<h2>Status: Completed!</h2>
	<p> Date Completed: <%=@pickup.updated_at%></p>
<% else %>
	<h2>Status: Pending</h2>
<% end %>
 
<div class="col-md-2">
	<p>Pieces in Pickup: <%= @pickup.piececount %> </p>
	<p>Associated Pieces: <%= @pickup.pieces.count %> </p>

	<% if @pickup.completed != true %>

		<p><%=link_to "Edit Pickup Details", edit_pickup_path(@pickup)%>
		<p><%=link_to "Delete Pickup", @pickup, method: :delete, data: {confirm: "Are you sure?"} %> </p>

		<p><%=link_to "+ Check In Pieces", pickup_check_in_pieces_path(@pickup, :client_id => @pickup.client.id)%></p>

		<p><%=link_to "+ Create New Pieces", new_client_piece_path(@client_id, :pickup_id => @pickup.id) %> </p>

	<%end%>


	<% if @pickup.notes.present? %>
		<p> Notes: <%= @pickup.notes %> </p>
	<%end%>
	
	
	<% if @pickup.completed != true %>	
		<br><%=button_to "Complete Pickup", completed_client_pickups_path(@pickup.client_id, :pickup_id => @pickup.id), method: "put", data: { confirm: "Are you sure?"} %></br>
	<%else%>
		<br><%=button_to "Unmark as Complete", completed_client_pickups_path(@pickup.client_id, :pickup_id => @pickup.id), method: "put", data: { confirm: "Are you sure you want to unmark Pickup # #{@pickup.id} as complete?"}%></br>

	<% end %>
</div>

<div class="col-md-10">

	<h3> <u> Pieces from Pickup </u> </h3>

	<%= form_tag pickup_remove_piece_path(@pickup.id), method: :put do %>

		<%@pickup.pieces.each do |p|%>
			<ul class="all-pieces-grid">
				<%= link_to image_tag(p.photo), p %>
				<center> <%= check_box_tag "piece_ids[]", p.id %>
				Piece #:<%= p.id %>
				<p>Designer: <%= p.designer %></p>
				Description: <%= p.description %></center>
			</ul>
		<%end%>

		<% if @pickup.pieces != [] %>
		<br> <%= submit_tag "Remove Pieces from Pickup" %> </br>
		<%end%>
	<%end%>

	<br><%=link_to "Return to Client Page", client_path(@client_id) %></br>

</div>