config/routes.rb
Rails.application.routes.draw do
  
  devise_for :collection_managers
  devise_for :admin_users

  root 'dashboard#index'
    get 'completed' => "dashboard#completed"

  resources :admin_users do
    resources :collection_managers do
    end
  end

  resources :collection_managers, shallow: true do
    resources :clients do
        get 'profile' => "clients#profile"
      resources :pieces do
        get 'garments', on: :collection
        get 'bags', on: :collection
        get 'shoes', on: :collection
        get 'accessories', on: :collection
      end
      resources :deliveries do
        get 'completed_deliveries', on: :collection
        collection do
            put :completed
        end
          get 'check_out_pieces' => "deliveries#check_out"
          put 'complete_check_out' => "deliveries#complete_check_out"
          put 'remove_piece' => 'deliveries#remove'
        end
      resources :pickups do
        get 'completed_pickups', on: :collection
        collection do
            put :completed
        end
        get 'check_in_pieces' => "pickups#check_in"
        put 'complete_check_in' => "pickups#complete_check_in"
        put 'remove_piece' => 'pickups#remove'
        resources :pieces
      end
    end
  end
end

app/models/client.rb
class Client < ActiveRecord::Base
  belongs_to :collection_manager
  has_many :pieces
  has_many :deliveries
  has_many :pickups

def self.search_for(search)
  where("name LIKE ?", "%#{search}%")
end

has_attached_file :photo, 
          styles: {
                thumb: '100x100>',
                square: '200x200#',
                medium: '300x300>'
              },
          :bucket => :fashionarchive

  # Validate the attached image is image/jpg, image/png, etc
  validates_attachment_content_type :photo, :content_type => /\Aimage\/.*\Z/
 
  

 
  
end

app/controllers/clients_controller.rb
class ClientsController < ApplicationController
	
	def index
		@collection_manager = current_collection_manager
		@clients = @collection_manager.clients.all
		if params[:search]
			@clients = @clients.search(params[:search])
		else
			@clients
		end
	end

	def new
		@collection_manager = current_collection_manager
		@client = @collection_manager.clients.new
		
	end

	def create
		@collection_manager = current_collection_manager
		@client = @collection_manager.clients.create(safe_client_params)
		if @client.save
			flash[:notice] = "New Client has been created!"
			redirect_to collection_manager_clients_path(current_collection_manager)
		else
			flash[:alert] = "Please complete form."
			render :new
		end

	end

	def edit
		@client = Client.find(params[:id])

	end

	def update
		@client = Client.find(params[:id])
		
		if @client.update(safe_client_params)
			flash[:notice] = "Client Updated!"
			redirect_to client_profile_path(@client)
		else
			render edit_client_path
		end

	end

	def destroy
		@client = Client.find(params[:id]).destroy
		redirect_to collection_manager_clients_path(current_collection_manager)
	end

	def show
		@client = Client.find(params[:id])
		@piece_count = @client.pieces.count
		@pieces_on_site = @client.pieces.where(location: 'On Site')
		@pieces_at_client = @client.pieces.where(location: 'At Client').count

	end

	def profile
		@client = Client.find(params[:client_id])
		@pieces_on_site = @client.pieces.where(location: 'On Site')
		@pieces_at_client = @client.pieces.where(location: 'At Client').count
		@piece_count = @client.pieces.count
		

	end

	private

	def safe_client_params
		params.require(:client).permit(:name, :birthday, :email, :email_assist, :cell_phone, :delivery_pref, :photo)
	end


end

app/views/clients/_client_menu.html.erb
<br>Pieces at Client: <%= @pieces_at_client %></br>
<p>Total Piece Count: <%= @piece_count %></p>
<p><%= link_to "View All Pieces", client_pieces_path(@client) %></p>
<p><%=link_to "+ New Pickup", new_client_pickup_path(@client)%></p>
<p><%= link_to "Pending Pickups", client_pickups_path(@client.id) %> </p>
<p><%=link_to "+ New Delivery", new_client_delivery_path(@client)%></p>
<p><%= link_to "Pending Deliveries", client_deliveries_path(@client.id) %> </p>

app/views/clients/edit.html.erb
<h1>Edit <%=@client.name%>'s Profile</h1>

<%=form_for @client do |c|%>
	<p>PHOTO: <%= c.file_field :photo %></p>
	<p>NAME: <%= c.text_field :name %></p>
	<p>ADDRESS: <%= c.text_area :address %></p>
	<p>E-MAIL: <%=c.text_field :email%></p>
	<p>ASSISTANT'S EMAIL: <%=c.text_field :email_assist%></p>
	<p>BIRTHDAY: <%=c.text_field :birthday%></p>
	<p>CELL PHONE: <%=c.text_field :cell_phone%></p>
	<p>DELIVERY PREFERENCES: <%=c.text_area :delivery_pref%></p>

<p><%=c.submit%></p>

<%end%>

app/views/clients/index.html.erb
<h2><%=@collection_manager.name%>'s Clients</h2>
<div class="col-md-2">
	<%=link_to "+ Add New Client", new_collection_manager_client_path(current_collection_manager)%>
</div>

<div class="col-md-10">

	<%if @clients.empty? %>
		<br><%= @collection_manager.name %> currently has no clients.</br>
	<%else%>
		<table class="table table-bordered table-striped">
			<thead>
				<tr>
					<th>Name</th>
					<th>Total Pieces</th>
				</tr>
			</thead>
			<tbody>
				<%@clients.each do |view|%>
					<tr>
						<td><%=link_to view.name, view%></td>
						<td><%=view.pieces.count%></td>
					</tr>
				<%end%>
			</tbody>
		</table>
	<%end%>
<br><%= link_to "Return to Dashboard", root_path %></br>

</div>

app/views/clients/new.html.erb
<h1> Create New Client</h1>

	<%=form_for [current_collection_manager, @client] do |c|%>
		<p>PHOTO: <%=c.file_field :photo%></p>
		<p>NAME: <%=c.text_field :name%></p>
		<p>ADDRESS: <%=c.text_area :address%></p>
		<p>E-MAIL: <%=c.text_field :email%></p>
		<p>ASSISTANT'S EMAIL: <%=c.text_field :email_assist%></p>
		<p>BIRTHDAY: <%=c.text_field :birthday%></p>
		<p>CELL PHONE: <%=c.text_field :cell_phone%></p>
		<p>DELIVERY PREFERENCES: <%=c.text_area :delivery_pref%></p>

	<p><%=c.submit class: "btn btn-default btn-md"%></p>

<%end%>

app/views/clients/profile.html.erb
<div class="col-md-2">

	<%= render "client_menu" %>

</div>

<div class="col-md-10">

<h1><%=@client.name%>'s Profile</h1>

	<p><img src = <%=@client.photo%> height=300></p>
	<p><%=link_to "Edit Profile", edit_client_path(@client)%> | <%=link_to "Delete Client", @client, method: :delete, data: {confirm: "Are you sure you want to delete #{@client.name}?"} %></p>

	<p>ADDRESS: <%=@client.address%></p>
	<p>E-MAIL: <%=@client.email%></p>
	<p>PHONE: <%=@client.cell_phone%></p>
	<p>BIRTHDAY: <%=@client.birthday%></p>
	<p>DELIVERY PREFERENCES: <%=@client.delivery_pref%></p>


	<br><%=link_to "Return to Client Page", client_path(@client) %></br>

</div>

app/views/clients/show.html.erb
<div class="col-md-2">

<%= render "client_menu" %>

</div>

<div class="col-md-10">
  <h1> <u> <%=@client.name%> </u> </h1>
    <p><%= link_to "View Profile", client_profile_path(@client) %></p>

<h3> Pieces On Site </h3>
	<%if @pieces_on_site.empty? %>
	   <br>There are currently no pieces in <%=@client.name%>'s archive.</br>
	<%end%>
  
  <%@pieces_on_site.each do |show|%>
    <ul class="all-pieces-grid">
      <p><%= link_to image_tag(show.photo), show %></p>
      <center><p>Piece #: <%=show.id%></p>
      Designer: <%=show.designer%></center>
    </ul>
  <%end%>


  
</div>