config/routes.rb
Rails.application.routes.draw do
  
  devise_for :collection_managers
  devise_for :admin_users

  root 'dashboard#index'
    get 'completed' => "dashboard#completed"

  resources :admin_users do
    resources :collection_managers do
    end
  end

  resources :collection_managers, shallow: true do
    resources :clients do
        get 'profile' => "clients#profile"
      resources :pieces do
        get 'garments', on: :collection
        get 'bags', on: :collection
        get 'shoes', on: :collection
        get 'accessories', on: :collection
      end
      resources :deliveries do
        get 'completed_deliveries', on: :collection
        collection do
            put :completed
        end
          get 'check_out_pieces' => "deliveries#check_out"
          put 'complete_check_out' => "deliveries#complete_check_out"
          put 'remove_piece' => 'deliveries#remove'
        end
      resources :pickups do
        get 'completed_pickups', on: :collection
        collection do
            put :completed
        end
        get 'check_in_pieces' => "pickups#check_in"
        put 'complete_check_in' => "pickups#complete_check_in"
        put 'remove_piece' => 'pickups#remove'
        resources :pieces
      end
    end
  end
end

app/models/delivery.rb
class Delivery < ActiveRecord::Base
  belongs_to :client
  has_many :pieces

  validates :date, presence: true
  validates :piececount, presence: true
  
end

app/controllers/deliveries_controller.rb
class DeliveriesController < ApplicationController


	def index
		@collection_manager = current_collection_manager
		@client = @collection_manager.clients.find(params[:client_id])
		@deliveries = @client.deliveries
		@pending_deliveries = @deliveries.where(completed: nil)

	end

	def show
		@delivery = Delivery.find(params[:id])
		@client_name = @delivery.client.name
		@client_id = @delivery.client_id
		@pieces = @delivery.pieces

	end

	def new
		@client = Client.find(params[:client_id])
		@delivery = @client.deliveries.new

	end

	def create
		@client = Client.find(params[:client_id])
		@delivery = @client.deliveries.create(safe_delivery_params)
		if @delivery.save
			flash[:notice] = "Delivery created!"
			redirect_to delivery_path(@delivery)
		else
			flash[:alert] = "Please complete delivery form!"
			render :new
		end
	end

	def edit
		@delivery = Delivery.find(params[:id])
		@client = @delivery.client

	end

	def update
		@delivery = Delivery.find(params[:id])
		if @delivery.update(safe_delivery_params)
			flash[:notice] = "Delivery updated!"
			redirect_to delivery_path(@delivery)
		else
			render edit_delivery_path
		end
	end


	def check_out
		@client_id = params[:client_id]
		@client = Client.find(@client_id)
		@pieces = @client.pieces.where(location: 'On Site')
	end

	def complete_check_out
		@delivery = Delivery.find(params[:delivery_id])
		@client = @delivery.client_id
		Piece.where(id: params[:piece_ids]).update_all(location: "At Client", delivery_id: @delivery)
		redirect_to delivery_path(@delivery)

	end

	def destroy
		@delivery = Delivery.find(params[:id]).destroy
		@client = @delivery.client
		redirect_to client_path(@client)
	end

	def completed
		@delivery = Delivery.find(params[:delivery_id])
		if @delivery.completed != true
			if @delivery.pieces.count != @delivery.piececount
				flash[:alert] = "Pieces in delivery must equal number of associated pieces!"
				redirect_to delivery_path(@delivery)	
			else 
				@delivery.update(completed: true)
				flash[:notice] = "Delivery has been marked as complete!"
				redirect_to delivery_path(@delivery)
			end
		else
			@delivery.update(completed: false)
			redirect_to delivery_path(@delivery)
		end
	end

	def completed_deliveries
		@client = Client.find(params[:client_id])
		@deliveries = @client.deliveries.where(completed: true)
	end

	def remove
		@delivery = Delivery.find(params[:delivery_id])
		@client = @delivery.client_id
		Piece.where(id: params[:piece_ids]).update_all(location: "On Site", delivery_id: 'nil')
		redirect_to delivery_path(@delivery)
	end


	private

	def safe_delivery_params

		params.require(:delivery).permit(:date, :notes, :client_id, :piececount)

	end


end

app/views/deliveries/check_out.html.erb
<div class="col-md-2">

	

</div>

<div class="col-md-10">
	<h1>Select Pieces in <%=@client.name%>'s Archive to Check out</h1>

	<h3>Pieces On Site </h3>

	<% if @pieces.empty? %>
		<br>There are currently no pieces on site to check out.</br>

	<%else%>
		<%= form_tag delivery_complete_check_out_path, method: :put do %>
			<%@pieces.each do |show|%>
				<ul class="all-pieces-grid">
					<img src = <%=show.photo%>>
					<br>Designer: <%=show.designer%></br>
					<%= check_box_tag "piece_ids[]", show.id %>  #<%=show.id%>
				</ul>
			<%end%>
			<p><%= submit_tag "Check Out Pieces" %> </p>
		<%end%>
	<%end%>

<br><%=link_to "Return to Client Page", client_path(@client) %></br>

</div>

app/views/deliveries/completed_deliveries.html.erb
<h1> Completed Deliveries for <%=@client.name%> </h1>

<div class="col-md-2">
	<p><%=link_to "+ New Delivery", new_client_delivery_path(@client)%></p>
</div>

<div class="col-md-10">
	<% if @deliveries.empty? %>
			<p>All deliveries are currently pending.</p>
		<%else%>
			<table class="table table-bordered table-striped">
				<thead>
					<tr>
						<th>Date</th>
						<th>Delivery Number</th>
						<th>Client</th>
						<th>Number of Pieces</th>
					</tr>
				</thead>
				<tbody>	
					<%@deliveries.each do |d|%>
						<tr>
							<td><%= link_to d.date.strftime("%m/%d/%Y"), d %></td>
							<td><%= d.id%></td>
							<td><%= d.client.name%></td>
							<td><%= d.piececount%></td>
						</tr>
					<%end%>	
				</tbody>
			</table>
		<%end%>

<br><%=link_to "Return to Client Page", client_path(@client) %></br>
</div>

app/views/deliveries/edit.html.erb
<h1> Delivery for <%=@client.name%></h1>

<h2> Edit Delivery </h2>

<%= form_for [@delivery] do |d|%>
	<p>Date: <%= d.date_select :date %></p>

	<p>Piece Count: <%= d.text_field :piececount %>
	<p>Notes: <%= d.text_area :notes %>
	

	<p><%= d.submit %></p>

<%end%>

app/views/deliveries/index.html.erb
<h2>Pending Deliveries for <%=@client.name%></h2>

<div class="col-md-2">
	<p><%=link_to "+ New Delivery Request", new_client_delivery_path(@client)%></p>
	<p><%=link_to "Completed Deliveries", completed_deliveries_client_deliveries_path(@client) %></p>

</div>

<div class="col-md-10">

		<% if @pending_deliveries.blank? %>
			<p>There are currently no pending deliveries.</p>
		<%else%>

			<br><table class="table table-bordered table-striped">
				<thead>
					<tr>
						<th>Date</th>
						<th>Delivery Number</th>
						<th>Client</th>
						<th>Number of Pieces</th>
					</tr>
				</thead>
				<tbody>
						
					<%@pending_deliveries.each do |d|%>
					<tr>
						<td><%= link_to d.date.strftime("%m/%d/%Y"), d %></td>
						<td><%= d.id%></td>
						<td><%= d.client.name%></td>
						<td><%= d.piececount%></td>
					</tr>
					<%end%>
						
				</tbody>
			</table></br>
		<%end%>

	<br><%=link_to "Return to Client Page", client_path(@client) %></br>
</div>



	

app/views/deliveries/new.html.erb
<h1> New Delivery Request for <%=@client.name%></h1>

<div class="col-md-10">
	<%= form_for [@client, @delivery] do |d|%>
		<p>Date: <%= d.date_select :date %></p>

		<p>Piece Count: <%= d.text_field :piececount %>
		<p>Notes: <%= d.text_area :notes %>
		

		<p><%= d.submit class: "btn btn-default btn-md"%></p>

	<%end%>

<br><%=link_to "Return to Client Page", client_path(@client) %></br>
</div>

app/views/deliveries/show.html.erb
<h1>Delivery #<%=@delivery.id%> on <%=@delivery.date.strftime("%m/%d/%Y") %> for <%=@client_name%></h1>

	<% if @delivery.completed? %>
		<h2>Status: Completed!</h2>
		<p> Date Completed: <%=@delivery.updated_at%></p>
	<% else %>
		<h2>Status: Pending</h2>
	<% end %>
 
<div class="col-md-2">
	<p>Total Pieces in Delivery: <%=@delivery.piececount%></p>
	<p>Pieces Associated with Delivery: <%=@delivery.pieces.count%></p>


	<% if @delivery.completed != true %>
		
		<p><%=link_to "Edit Delivery Details", edit_delivery_path(@delivery)%>
		
		<p><%=link_to "Delete Delivery", @delivery, method: :delete, data: {confirm: "Are you sure?"} %> </p>

		<p><%=link_to "+ Check Out Pieces", delivery_check_out_pieces_path(@delivery, :client_id => @delivery.client.id)%></p>
	<%end%>

	<% if @delivery.notes.present? %>
		<p> Notes: <%= @delivery.notes %> </p>
	<%end%>
	
	<% if @delivery.completed != true %>	

		<br><%=button_to "Complete Delivery",completed_client_deliveries_path(@delivery.client_id, :delivery_id => @delivery.id), method: "put", data: { confirm: "Are you sure?"} %> </br>
	<%else%>

		<br><%=button_to "Unmark as Complete", completed_client_deliveries_path(@delivery.client_id, :delivery_id => @delivery.id), method: "put", data: { confirm: "Are you sure you want to unmark Delivery # #{@delivery.id} as complete?"}%> </br>
	<% end %>
</div>

<div class="col-md-10">

	<h3> <u> Pieces in Delivery </u> </h3>

	<% if @delivery.completed != true %>

		<%= form_tag delivery_remove_piece_path(@delivery.id), method: :put do %>

			<% @pieces.each do |show| %>
				<ul class="all-pieces-grid">
					<center><%= link_to image_tag(show.photo), show %>
					<%= check_box_tag "piece_ids[]", show.id %>
					Piece #:<%= show.id %>
					<p>Designer: <%= show.designer %></p></center>
				</ul>
			<%end%>
			<% if @delivery.pieces != [] %>
				<br> <%= submit_tag "Remove Pieces from Delivery" %> </br>
			<%end%>
		<%end%>
	<%else%>
		<% @pieces.each do |show| %>
			<ul class="all-pieces-grid">
				<%= link_to image_tag(show.photo), show %>
				<center><p>Piece #: <%= show.id %></p>
				<p>Designer: <%= show.designer %></p></center>
			</ul>
		<%end%>

	<%end%>


<br><%=link_to "Return to Client Page", client_path(@delivery.client.id) %></br>

</div>