config/routes.rb
Rails.application.routes.draw do
  
  devise_for :collection_managers
  devise_for :admin_users

  root 'dashboard#index'
    get 'completed' => "dashboard#completed"

  resources :admin_users do
    resources :collection_managers do
    end
  end

  resources :collection_managers, shallow: true do
    resources :clients do
        get 'profile' => "clients#profile"
      resources :pieces do
        get 'garments', on: :collection
        get 'bags', on: :collection
        get 'shoes', on: :collection
        get 'accessories', on: :collection
      end
      resources :deliveries do
        get 'completed_deliveries', on: :collection
        collection do
            put :completed
        end
          get 'check_out_pieces' => "deliveries#check_out"
          put 'complete_check_out' => "deliveries#complete_check_out"
          put 'remove_piece' => 'deliveries#remove'
        end
      resources :pickups do
        get 'completed_pickups', on: :collection
        collection do
            put :completed
        end
        get 'check_in_pieces' => "pickups#check_in"
        put 'complete_check_in' => "pickups#complete_check_in"
        put 'remove_piece' => 'pickups#remove'
        resources :pieces
      end
    end
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>FashionArchive</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>

  <%= csrf_meta_tags %>
</head>
<body>
 <% if collection_manager_signed_in?%>

<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/">TFA</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li class="active"><li><%=link_to "Clients", collection_manager_clients_path(current_collection_manager)%></li></span></a></li>
      </ul>
      <form class="navbar-form navbar-left" role="search">
        <div class="form-group">
          <%= form_tag root_path, class: 'navbar-form' do %>
              <div class = "input-group">
                <%= search_field_tag :search, "", placeholder: "Search Clients", class: "form-control"%>
              </div>
              <div class = "input-group">
                <%= submit_tag "Search", class: "btn btn-default" %>
              </div>
          <%end%> 
          <button type="submit" class="btn btn-default">Submit</button>
        </div>
      </form>
      <ul class="nav navbar-nav navbar-right">
        
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"> <%=current_collection_manager.name%> <span class="caret"></span></a>
          <ul class="dropdown-menu">
             
              <li><%= link_to 'Edit Profile', edit_collection_manager_registration_path %> </li>
              <li><%= link_to "Logout", destroy_collection_manager_session_path, method: :delete %> </li>
              
              <%end%>
          </ul>
        </li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>



<% if notice %>
  <p class="alert alert-success"><%= notice %></p>
<% end %>
<% if alert %>
  <p class="alert alert-danger"><%= alert %></p>
<% end %>

<div class ="container">
  <div class = "row">


<%= yield %>


</div>
</div>

</body>
</html>